.PHONY: copy-libs

copy-libs:
	rm -rf lib

	mkdir -p lib/system/timer
	cp -r ../../../libs/system/timer/* lib/system/timer

	mkdir -p lib/communication/radio_transmitter
	cp -r ../../../libs/communication/radio_transmitter/* lib/communication/radio_transmitter/