.PHONY: copy-libs

copy-libs:
	rm -rf lib

	mkdir -p lib/system/timer
	cp -r ../../libs/system/timer/* lib/system/timer

	mkdir -p lib/input/joystick
	cp -r ../../libs/input/joystick/* lib/input/joystick