; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_ldf_mode = deep+
lib_deps = 
    nrf24/RF24@^1.4.9

[env:box]
build_src_filter = +<../src/box/>
; upload_speed = 115200
; upload_protocol = arduino

[env:controller]
build_src_filter = +<../src/controller/>
upload_protocol = arduino
upload_speed = 115200
board_build.mcu = atmega328p
upload_flags =
    -D
    -V


[env:box2]
build_src_filter = +<../src/box2/>
; upload_speed = 115200
; upload_protocol = arduino

[env:box2_old_bootloader]
build_src_filter = +<../src/box2/>
upload_protocol = arduino
upload_speed = 57600
board_build.mcu = atmega328p
upload_flags =
    -D
    -V

[env:box2_new_bootloader]
build_src_filter = +<../src/box2/>
upload_protocol = arduino
upload_speed = 115200
board_build.mcu = atmega328p
upload_flags =
    -D
    -V

[env:motor_test]
build_src_filter = +<../src/motor_test/>
upload_protocol = arduino
upload_speed = 115200
board_build.mcu = atmega328p
upload_flags =
    -D
    -V

[env:joystick_test]
build_src_filter = +<../src/joystick_test/>
upload_protocol = arduino
upload_speed = 115200
board_build.mcu = atmega328p
upload_flags =
    -D
    -V