.PHONY: copy-libs

copy-libs:
	rm -rf lib/sensorsMotionDetector
	mkdir -p lib/sensorsMotionDetector
	cp ../../libs/sensors/MotionDetector/motion_detector.h lib/sensorsMotionDetector/
	cp ../../libs/sensors/MotionDetector/motion_detector.cpp lib/sensorsMotionDetector/
	cp ../../libs/sensors/MotionDetector/motion_detector_timer_adapter.h lib/sensorsMotionDetector/
	rm -rf lib/system/timer
	mkdir -p lib/system/timer
	cp ../../libs/system/timer/timer_control.h lib/system/timer/
	cp ../../libs/system/timer/timer_control.cpp lib/system/timer/
	cp ../../libs/system/timer/timer_handler.h lib/system/timer/