.PHONY: copy-wifi

copy-wifi:
	rm -rf lib/WifiManager
	mkdir -p lib/WifiManager/esp32
	cp ../../libs/WifiManager/wifi_manager.h lib/WifiManager/
	cp ../../libs/WifiManager/esp32/esp32_wifi_manager.cpp lib/WifiManager/esp32/
	cp ../../libs/WifiManager/esp32/esp32_wifi_manager.h lib/WifiManager/esp32/
